### ISSUE TITLE
Staged application can not start up

### ISSUE THREAD

**Issue by marc0der** [simonharrer/play-java-gradle-example#2]
When staging an application for deployment with `./gradlew stage`, and then attempt to run this staged app, the application cannot start up.

```
Oops, cannot start the server.
@71k3kk47b: Configuration error
	at play.api.libs.crypto.CryptoConfigParser.get$lzycompute(Crypto.scala:498)
	at play.api.libs.crypto.CryptoConfigParser.get(Crypto.scala:465)
	at play.api.libs.crypto.CryptoConfigParser.get(Crypto.scala:463)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        .....
```

Worth mentioning that this is with the default skeleton app in Java or Scala.

**Comment by marc0der** [comment]
False alarm, this seems to be a problem with the `play-scala` template project produced by activator.

**Comment by simonharrer** [comment]
Yes, but I do feel your pain. I had stumbled over this as well, especially when deploying to heroku, as the error message is not that super helpful. the reason is the missing application secret.

**Comment by marc0der** [comment]
Yes, I figured it out when running it from sbt. It does give a more elaborate error message.

BTW, thanks for the great template!

**Comment by simonharrer** [comment]
You are welcome. :)
